# Generated by Django 5.0.3 on 2024-03-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authenticatedusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthenticatedUsers',
            new_name='AuthenticatedUser',
        ),
    ]
