# Generated by Django 5.0.3 on 2024-03-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_authenticatedusers_authenticateduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dashboarduser', unique=True),
        ),
    ]
