# Generated by Django 5.0.3 on 2024-03-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_authenticateduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.dashboarduser'),
        ),
    ]
